---
name: mpileup
command: samtools mpileup
parameters:
  -f:
  -u:



# samtools mpileup -uf /scratch/summerschool/Data/Reference_Genomes/hsa_37.p5/hs_ref_GRCh37.p5_chr22.fa /scratch/summerschool/Data/Data_From_Tuebingen/NA12878_01.bam | bcftools view -bvcg - > var.raw.bcf
#  bcftools view var.raw.bcf | vcfutils.pl varFilter -d5 -D100 > var.flt.vcf